packages:
  - "integration"
  - "integration/helpers/node-template"
  - "integration/helpers/vite-template"
  - "packages/react-router"
  - "packages/react-router-dom"
  - "packages/react-router-dev"
  - "packages/react-router-express"
  - "packages/react-router-node"
  - "packages/react-router-serve"
  - "playground/compiler"
  - "playground/compiler-express"
  - "playground/compiler-spa"
