name: 🧪 Test (Integration)

on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-integration:
    name: "🧪 Integration Test: (Node: ${{ matrix.node }})"
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20.5.1

    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: ⎔ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          check-latest: true

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 📥 Install Playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: 🧪 Run tests
        run: pnpm test:integration
